### Auxiliary tables

# ALTERACION
REPLACE INTO eel_completa.ALTERACION
SELECT * FROM eel2013.ALTERACION;

#ATAQUE
REPLACE INTO eel_completa.ATAQUE
SELECT * FROM eel2013.ATAQUE;

#CAUSA
REPLACE INTO eel_completa.CAUSA
SELECT * FROM eel2013.CAUSA;

#CAUSANTE
REPLACE INTO eel_completa.CAUSANTE
SELECT * FROM eel2013.CAUSANTE;

#CAUSAS
REPLACE INTO eel_completa.CAUSAS
SELECT * FROM eel2013.CAUSAS;

#CLASEDIA
REPLACE INTO eel_completa.CLASEDIA
SELECT * FROM eel2013.CLASEDIA;

#DETECTADOPOR
REPLACE INTO eel_completa.DETECTADOPOR
SELECT * FROM eel2013.DETECTADOPOR;

#EFECTOVSYEL
REPLACE INTO eel_completa.EFECTOVSYEL
SELECT * FROM eel2013.EFECTOVSYEL;

#ESPECIES
REPLACE INTO eel_completa.ESPECIES
SELECT * FROM eel2013.ESPECIES;

#GRUPOCAUSAS
REPLACE INTO eel_completa.GRUPOCAUSAS
SELECT * FROM eel2013.GRUPOCAUSAS;

#IDIOMAS
REPLACE INTO eel_completa.IDIOMAS
SELECT * FROM eel2013.IDIOMAS;

#INCIDENCIASPC
REPLACE INTO eel_completa.INCIDENCIASPC
SELECT * FROM eel2013.INCIDENCIASPC;

#INICIADOJUNTOA
REPLACE INTO eel_completa.INICIADOJUNTOA
SELECT * FROM eel2013.INICIADOJUNTOA;

#MEDIOSTRANSPORTE
REPLACE INTO eel_completa.MEDIOSTRANSPORTE
SELECT * FROM eel2013.MEDIOSTRANSPORTE;

#MODELOSCOMBUSTIBLE
REPLACE INTO eel_completa.MODELOSCOMBUSTIBLE
SELECT * FROM eel2013.MODELOSCOMBUSTIBLE;

#MOTIVACION
REPLACE INTO eel_completa.MOTIVACION
SELECT * FROM eel2013.MOTIVACION;

#PELIGRO
REPLACE INTO eel_completa.PELIGRO
SELECT * FROM eel2013.PELIGRO;

#PRODUCTOS
REPLACE INTO eel_completa.PRODUCTOS
SELECT * FROM eel2013.PRODUCTOS;

#REL_TIPOSENP
REPLACE INTO eel_completa.REL_TIPOSENP
SELECT * FROM eel2013.REL_TIPOSENP;

#REROSION
REPLACE INTO eel_completa.REROSION
SELECT * FROM eel2013.REROSION;

#RETARDANTE
REPLACE INTO eel_completa.RETARDANTE
SELECT * FROM eel2013.RETARDANTE;

#SINO
REPLACE INTO eel_completa.SINO
SELECT * FROM eel2013.SINO;

#SITUACIONLM
REPLACE INTO eel_completa.SITUACIONLM
SELECT * FROM eel2013.SITUACIONLM;

#SUPARBOLADAAFAUTOR
REPLACE INTO eel_completa.SUPARBOLADAAFAUTOR
SELECT * FROM eel2013.SUPARBOLADAAFAUTOR;

#TECNICAATAQUEINDIRECTO
REPLACE INTO eel_completa.TECNICAATAQUEINDIRECTO
SELECT * FROM eel2013.TECNICAATAQUEINDIRECTO;

#TIPOENPDESCRIPCION
REPLACE INTO eel_completa.TIPOENPDESCRIPCION
SELECT * FROM eel2013.TIPOENPDESCRIPCION;

#TIPOFUEGO
REPLACE INTO eel_completa.TIPOFUEGO
SELECT * FROM eel2013.TIPOFUEGO;

#TIPORENTA
REPLACE INTO eel_completa.TIPORENTA
SELECT * FROM eel2013.TIPORENTA;

#TIPOSENP
REPLACE INTO eel_completa.TIPOSENP
SELECT * FROM eel2013.TIPOSENP;

### Administrative tables

#COMARCAOISLA
REPLACE INTO eel_completa.COMARCAOISLA
SELECT * FROM eel2013.COMARCAOISLA;

#COMUNIDADES
REPLACE INTO eel_completa.COMUNIDADES
SELECT * FROM eel2013.COMUNIDADES;

#ENTIDADESMENORES
REPLACE INTO eel_completa.ENTIDADESMENORES
SELECT * FROM eel2013.ENTIDADESMENORES;

#MUNICIPIOS
REPLACE INTO eel_completa.MUNICIPIOS
SELECT * FROM eel2013.MUNICIPIOS;

#PROVINCIAS
REPLACE INTO eel_completa.PROVINCIAS
SELECT * FROM eel2013.PROVINCIAS;

### National and natural parks tables

#ENP
REPLACE INTO eel_completa.ENP
SELECT * FROM eel2013.ENP;

#MONTES
REPLACE INTO eel_completa.MONTES
SELECT * FROM eel2013.MONTES;

### Weather stations

#ESTACIONESMETEOROLOGICAS
REPLACE INTO eel_completa.ESTACIONESMETEOROLOGICAS
SELECT * FROM eel2013.ESTACIONESMETEOROLOGICAS;

### Hired personnel

#VIGILANTEFIJO
REPLACE INTO eel_completa.VIGILANTEFIJO
SELECT * FROM eel2013.VIGILANTEFIJO;

### Empty tables

#AGRUPACIONDEMUNICIPIOS
REPLACE INTO eel_completa.AGRUPACIONDEMUNICIPIOS
SELECT * FROM eel2013.AGRUPACIONDEMUNICIPIOS;

#AGRUPACIONDETALLE
REPLACE INTO eel_completa.AGRUPACIONDETALLE
SELECT * FROM eel2013.AGRUPACIONDETALLE;





