# PIF TABLES

# PIF0
INSERT INTO eel_completa.PIF0
SELECT * FROM eel2013.PIF0;

# PIF1
INSERT INTO eel_completa.PIF1
SELECT * FROM eel2013.PIF1;

# PIF2
INSERT INTO eel_completa.PIF2
SELECT * FROM eel2013.PIF2;

# PIF3
INSERT INTO eel_completa.PIF3
SELECT * FROM eel2013.PIF3;

# PIF4
INSERT INTO eel_completa.PIF4
SELECT * FROM eel2013.PIF4;

# PIF5
INSERT INTO eel_completa.PIF5
SELECT * FROM eel2013.PIF5;

# PIF6
INSERT INTO eel_completa.PIF6
SELECT * FROM eel2013.PIF6;

# PIF7
INSERT INTO eel_completa.PIF7
SELECT * FROM eel2013.PIF7;

# PIF8
INSERT INTO eel_completa.PIF8
SELECT * FROM eel2013.PIF8;

# PIF9
INSERT INTO eel_completa.PIF9
SELECT * FROM eel2013.PIF9;

# PIF10
INSERT INTO eel_completa.PIF10
SELECT * FROM eel2013.PIF10;

# PDPM TABLES

# PDPM0
INSERT INTO eel_completa.PDPM0
SELECT * FROM eel2013.PDPM0;

# PDPM1
INSERT INTO eel_completa.PDPM1
SELECT * FROM eel2013.PDPM1;

# PDPM2
INSERT INTO eel_completa.PDPM2
SELECT * FROM eel2013.PDPM2;

# PDPM3
INSERT INTO eel_completa.PDPM3
SELECT * FROM eel2013.PDPM3;

# PDPM4
INSERT INTO eel_completa.PDPM4
SELECT * FROM eel2013.PDPM4;

# PDPM5
INSERT INTO eel_completa.PDPM5
SELECT * FROM eel2013.PDPM5;

# PDPM6
INSERT INTO eel_completa.PDPM6
SELECT * FROM eel2013.PDPM6;

# PDPM7
INSERT INTO eel_completa.PDPM7
SELECT * FROM eel2013.PDPM7;

# PENP TABLE

# PENP
INSERT INTO eel_completa.PENP
SELECT * FROM eel2013.PENP;

# REL_PIF3_VIGILANTEFIJO TABLE

# REL_PIF3_VIGILANTEFIJO
INSERT INTO eel_completa.REL_PIF3_VIGILANTEFIJO
SELECT * FROM eel2013.REL_PIF3_VIGILANTEFIJO;

# VALORACIONES TABLES

#ESPECIES_VALORACION
INSERT INTO eel_completa.ESPECIES_VALORACION
SELECT * FROM eel2013.ESPECIES_VALORACION;

#PRODUCTOS_VALORACION
INSERT INTO eel_completa.PRODUCTOS_VALORACION
SELECT * FROM eel2013.PRODUCTOS_VALORACION;

#TIPORENTA_VALORACION
INSERT INTO eel_completa.TIPORENTA_VALORACION
SELECT * FROM eel2013.TIPORENTA_VALORACION;


